domain: example.com
labs:
  - name: dojo-basic
    docker_compose: docker_compose_templates/dojo-basic.yaml
    subdomain_routes:
      main: web_port
  - name: juice-shop
    docker_compose: docker_compose_templates/juice-shop.yaml
    subdomain_routes:
      main: web_port