domain: example.com
labs:
  - name: dojo-basic
    docker_compose: docker_compose_templates/dojo-basic.yaml
    subdomain_routes:
      main: web_port
  - name: juice-shop
    docker_compose: docker_compose_templates/juice-shop.yaml
    subdomain_routes:
      main: web_port
  - name: wayfarer
    docker_compose: docker_compose_templates/wayfarer.yaml
    subdomain_routes:
      app: web_port
      api: api_port
  - name: musashi-js
    docker_compose: docker_compose_templates/musashi-js.yaml
    subdomain_routes:
      cors: cors_client_port
      api: cors_api_port
      csp: csp_app_port
      jwt: jwt_port