version: '3'
services:
  basicdb:
    image: ghcr.io/samuraiwtf/dojo-basic-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: samurai
      MYSQL_DATABASE: samurai_dojo_basic
    container_name: '{{ student_id }}_{{ lab_id }}_db'

  dojo-basic:
    image: ghcr.io/samuraiwtf/dojo-basic:latest
    ports:
      - "{{ web_port }}:80"
    links:
      - basicdb
    depends_on:
      - basicdb
    container_name: '{{ student_id }}_{{ lab_id }}_web'
    labels:
      - 'lab_id={{ lab_id }}'
      - 'student_id={{ student_id }}'


