version: '3'
services:
  dojo-basic_{{ student_id }}:
    image: ghcr.io/samuraiwtf/dojo-scavenger-lite:latest
    ports:
      - "{{ web_port }}:80"
    container_name: '{{ student_id }}_{{ lab_id }}'
    labels:
      - 'lab_id={{ lab_id }}'
      - 'student_id={{ student_id }}'
    restart: unless-stopped

